In [1]:
from sklearn.metrics import *
from urllib import *
from pandas.io.json import json_normalize
from urllib.request import urlretrieve
from PIL import Image, ImageDraw, ImageOps
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import json
import requests
import re
import os
import shutil
import ast
import csv

In [2]:
os.getcwd()

'C:\\Users\\rajeshs2\\MyDocuments\\Digital Lighthouse\\trash_detection'

In [2]:
df_annotation = pd.read_csv('annotations.csv')
df_annotation.head()

,filename,file_size,file_attributes,region_count,region_id,region_shape_attributes,region_attributes,Flag
0,seq_000473.jpg,39963,{},13,0,"{""name"":""rect"",""x"":111,""y"":338,""width"":35,""hei...","{""class_labels"":""human""}",Train
1,seq_000473.jpg,39963,{},13,1,"{""name"":""rect"",""x"":163,""y"":346,""width"":31,""hei...","{""class_labels"":""human""}",Train
2,seq_000473.jpg,39963,{},13,2,"{""name"":""rect"",""x"":468,""y"":364,""width"":29,""hei...","{""class_labels"":""human""}",Train
3,seq_000473.jpg,39963,{},13,3,"{""name"":""rect"",""x"":415,""y"":151,""width"":20,""hei...","{""class_labels"":""human""}",Train
4,seq_000473.jpg,39963,{},13,4,"{""name"":""rect"",""x"":451,""y"":145,""width"":20,""hei...","{""class_labels"":""human""}",Train

In [3]:
def extract_dict_values(x):
    return x.get('class_labels')

In [4]:
df_annotation['annotation'] = df_annotation['region_attributes'].apply(lambda x: extract_dict_values(json.loads(x)))
df_annotation.dropna(inplace=True)

In [5]:
df_annotation.head()

,filename,file_size,file_attributes,region_count,region_id,region_shape_attributes,region_attributes,Flag,annotation
0,seq_000473.jpg,39963,{},13,0,"{""name"":""rect"",""x"":111,""y"":338,""width"":35,""hei...","{""class_labels"":""human""}",Train,human
1,seq_000473.jpg,39963,{},13,1,"{""name"":""rect"",""x"":163,""y"":346,""width"":31,""hei...","{""class_labels"":""human""}",Train,human
2,seq_000473.jpg,39963,{},13,2,"{""name"":""rect"",""x"":468,""y"":364,""width"":29,""hei...","{""class_labels"":""human""}",Train,human
3,seq_000473.jpg,39963,{},13,3,"{""name"":""rect"",""x"":415,""y"":151,""width"":20,""hei...","{""class_labels"":""human""}",Train,human
4,seq_000473.jpg,39963,{},13,4,"{""name"":""rect"",""x"":451,""y"":145,""width"":20,""hei...","{""class_labels"":""human""}",Train,human

In [6]:
region_df = df_annotation['region_shape_attributes'].apply(json.loads).apply(pd.Series)

In [7]:
region_df.head()

   name    x    y  width  height
0  rect  111  338     35      33
1  rect  163  346     31      22
2  rect  468  364     29      34
3  rect  415  151     20      19
4  rect  451  145     20      20

In [8]:
final_df = pd.concat([df_annotation[['filename','annotation', 'Flag']], region_df], axis=1)

In [9]:
location_of_images = os.path.join('.','frames\\')

In [10]:
final_df['filename'] = location_of_images+ '' +final_df['filename']
final_df.head()

                  filename annotation   Flag  name    x    y  width  height
0  .\frames\seq_000473.jpg      human  Train  rect  111  338     35      33
1  .\frames\seq_000473.jpg      human  Train  rect  163  346     31      22
2  .\frames\seq_000473.jpg      human  Train  rect  468  364     29      34
3  .\frames\seq_000473.jpg      human  Train  rect  415  151     20      19
4  .\frames\seq_000473.jpg      human  Train  rect  451  145     20      20

In [11]:
dict_label = {'human':0}

In [12]:
final_df['label_int'] = final_df['annotation'].apply(lambda x: dict_label[x])
final_df['label_int'].head()

0    0
1    0
2    0
3    0
4    0
Name: label_int, dtype: int64

In [14]:
annotation_file = os.path.join(os.getcwd(), 'data', 'annotations_train.txt')
with open(annotation_file, 'a') as f:
    for i in range(len(final_df)):
        if final_df.iloc[i]['Flag'] == 'Train':
            x1 = int(final_df.iloc[i]['x'])
            y1 = int(final_df.iloc[i]['y'])
            x2 = int(final_df.iloc[i]['width'])
            y2 = int(final_df.iloc[i]['height'])
            label = str(final_df.iloc[i]['label_int'])
            coordination = [str(x1), str(x2), str(y1), str(y2)]
            record = final_df.iloc[i]['filename']+" "+','.join(coordination+[label])+'\n'
            f.write(record)
            
annotation_file = os.path.join(os.getcwd(), 'data', 'annotations_dev.txt')
with open(annotation_file, 'a') as f:
    for i in range(len(final_df)):
        if final_df.iloc[i]['Flag'] == 'Dev':
            x1 = int(final_df.iloc[i]['x'])
            y1 = int(final_df.iloc[i]['y'])
            x2 = int(final_df.iloc[i]['width'])
            y2 = int(final_df.iloc[i]['height'])
            label = str(final_df.iloc[i]['label_int'])
            coordination = [str(x1), str(x2), str(y1), str(y2)]
            record = final_df.iloc[i]['filename']+" "+','.join(coordination+[label])+'\n'
            f.write(record)
            
annotation_file = os.path.join(os.getcwd(), 'data', 'annotations_test.txt')
with open(annotation_file, 'a') as f:
    for i in range(len(final_df)):
        if final_df.iloc[i]['Flag'] == 'Holdout':
            x1 = int(final_df.iloc[i]['x'])
            y1 = int(final_df.iloc[i]['y'])
            x2 = int(final_df.iloc[i]['width'])
            y2 = int(final_df.iloc[i]['height'])
            label = str(final_df.iloc[i]['label_int'])
            coordination = [str(x1), str(x2), str(y1), str(y2)]
            record = final_df.iloc[i]['filename']+" "+','.join(coordination+[label])+'\n'
            f.write(record)

In [29]:
dev = {}
f_dev = open(os.path.join(os.getcwd(), 'data', 'annotations_dev.txt'), "r")

Lines_dev = f_dev.readlines()

for line in Lines_dev:
    filename, box = line.split()
    if filename not in dev:
        dev[filename] = []
    dev[filename].append(box)
    
file = open(os.path.join(os.getcwd(), 'input_log_utils_others', 'model_data', 'data_dev.txt'), 'w')
for k,v in dev.items():
    file.write(k+" "+ " ".join(v)+"\n")
file.close()

In [30]:
train = {}
f_train = open(os.path.join(os.getcwd(), 'data', 'annotations_train.txt'), "r")

Lines_train = f_train.readlines()

for line in Lines_train:
    filename, box = line.split()
    if filename not in train:
        train[filename] = []
    train[filename].append(box)
    
file = open(os.path.join(os.getcwd(), 'input_log_utils_others', 'model_data', 'data_train.txt'), 'w')
for k,v in train.items():
    file.write(k+" "+ " ".join(v)+"\n")
file.close()

In [31]:
predict = {}
f = open(os.path.join(os.getcwd(), 'data', 'annotations_test.txt'), "r")

Lines = f.readlines()

for line in Lines:
    filename, box = line.split()
    if filename not in predict:
        predict[filename] = []
    predict[filename].append(box)
    
file = open(os.path.join(os.getcwd(), 'input_log_utils_others', 'model_data', 'data_test.txt'), 'w')
for k,v in predict.items():
    file.write(k+" "+ " ".join(v)+"\n")
file.close()

In [32]:
shutil.copy('input_log_utils_others/model_data/data_test.txt','input_log_utils_others/model_data/data_test_updated.txt')

file = open('input_log_utils_others/model_data/data_test_updated.txt', "a")

for clean_image in os.listdir('data/clean_images'):
    file.write('./data/clean_images/'+clean_image+' '+ "10,30,40,50,15"+"\n")
file.close()